# COMS 3251 CLA Lab 1
### Due February 12th on Gradescope

---

William Xie, wx2214


Welcome to the first lab! This course will be taught in Python, a popular high-level language. Most COMS 4xxx courses are also taught in Python, so we recommend becoming familiar with the language as soon as possible. This lab assumes no prior knowledge of Python, but does assume that you already know Java or C.

By the way, if you already know Python, feel free to skip through to the actual homework problems. Open the **table of contents on the left** and jump to the PROBLEMs directly (after running the environment check cell below).

This lab is divided into three sections:
1. A basic python tutorial
2. Introduction to Numpy, a linear algebra-focused package
3. Implementations of various linear algebra topics covered during class

Before we begin, let's make sure your environment is set up correctly! Jupyter Notebook is divided into "cells" - this is a text cell, but the next one is a code cell that can be run! Go ahead and click the play button on the left (or hit shift-enter) to run the next block of code.

In [ ]:
# RUN THIS FIRST
# Environment check, one, two...

import numpy as np      # imports the numpy package
import math             # imports the math package
import sys, os          # imports system-related packages
import time             # imports time-related packages

print(sys.version)


3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]


If the above threw an error, make sure you have the numpy package installed. If the printed version starts with a "2." instead of a "3.", run the notebook in Python3, not Python2.

Before we start coding, let's cover some basic differences between Java and Python:

## Quick Intro to Python for Java Programmers

### 1. Java uses curly braces, Python uses indents.

You're probably familiar with the following piece of Java code:

```
if (isFriendly) {
    System.out.println("Hello World!");
}
```

Here, the indent isn't necessary or important - it's just there for us to read the code better. In fact, we could write it like this:

```
if (isFriendly) {
            System.out.println("Hello World!");}
```

and the code would still run. However, in python, **tabs define the block**, not curly braces:

```
if is_friendly:
    print("Hello World!")
```

Note that:
1. There are no parentheses after the if statement - they're optional.
2. The colon opens the next block of code, not a curly bracket
3. The second line of code is exactly one tab level in.

### 2. There are no semicolons in Python.

Instead, each line is assumed to be a single statement. In Java, you could do this:

```
System.out.println("ONE"); System.out.println("TWO");
```

But in python, they have to be on separate lines.

```
print("ONE")
print("TWO")
```

### 3. There's less overhead in Python.

Here's a full program for Hello World in Java.

```
public class HelloWorld {
    public static void main (String[] args) {
        System.out.println("Hello World!");
    }
}
```

and here's the equivalent in Python:

```
print("Hello World!")
```
neat!

### 4. Comments are hashtags, not double backslashes.

```
// this is a Java comment
# this is a Python comment

/* this is a Java block comment
 * that spans multiple lines
 */
# there is no such thing
# in python.
```

### 5. Variable types are assumed, not defined, and declarations are not required.

```
int a = 5;    // This is an int var "a", said Java.
a = 5         # This is a var "b" that I assume is int, said Python.

b = 6;        // You can't assign a value to an undeclared var! said Java.
b = 6         # This is a var "b" that I assume is int, said Python.
```

--------------------------

That should be enough to get started.

# Section 1: A Basic Python Tutorial

If, Else, While and For are fundamental control statements. You should already know what they are from Java, but let's cover the syntax.

In [ ]:
# Example 1: If/Else

x = 16

if x > 20:
    # print this statement if x is greater than 20
    print("x is greater than 20!")
else:
    # otherwise, print this statement.
    print("x is not greater than 20!")

# and/or

if x > 20 and x < 30:
    # if x is greater than 20 AND less than 30...
    # notice how legible this is! No && or ||.
    print("x is greater than 20 and less than 30")

if x > 20 or x % 2 == 0:
    # if x is greater than 20 OR divisible by 2...
    print("x is greater than 20 or divisible by 2")

x is not greater than 20!
x is greater than 20 or divisible by 2


In [ ]:
# Example 2: Introducing Elif

x = 16

if x > 20:
    print("x is greater than 20!")
elif x > 10:
    # Yes. We got lazy with writing "else if" so we created "elif".
    print("x is greater than 10, but not 20!")
else:
    print("x is not greater than 20 nor 10!")

x is greater than 10, but not 20!


In [ ]:
# Example 3: While
i = 0
while i < 5:            # check if i < 5 each iteration, stop looping otherwise.
    print("i =", i)     # print() can print multiple things separated by commas.
    i += 1              # shortened i = i + 1. i++ doesn't exist in python!

i = 0
i = 1
i = 2
i = 3
i = 4


In [ ]:
# Example 4: For (pun intended)

# range(0,5) generates the list [0,1,2,3,4].

for i in range(0,5):     # clever, right? no need for (int i=0; i<5; i++) here.
    print("i =", i)

i = 0
i = 1
i = 2
i = 3
i = 4


Example 5: Lists

The "for" example above gives us a good excuse to cover lists. Remember arrays in Java:

```
int[] intArray = new int[20];
```
In python, lists are basically Java arrays, but:
1. They can hold multiple types (strings, ints, etc.)
2. They don't have a defined size or memory allocation
3. They're very easy to use.

Check out some simple methods with lists below:

In [ ]:
# Example 5: Lists

# list with whatever we want in it
my_list = [1, "two", 3.0, 4]

# append "FIVE" to the end of my list
my_list.append("FIVE")
print(my_list)

# pop the last element from the end of my list
my_list.pop()
print(my_list)

# append two lists together
list_a = [1,2,3]
list_b = [4,5,6]
print(list_a + list_b)

# iterate through each item in a list
for item in my_list:
    print(item)

# check if an item exists in a list
if "three" in my_list:
    # "three" does exist in the list
    print("three is in list")
else:
    print("three is not in list")

# add items to a list in a loop
list_a = []
for i in range(5):
    # at each iteration, append i to the list
    list_a.append(i)
print(list_a)

[1, 'two', 3.0, 4, 'FIVE']
[1, 'two', 3.0, 4]
[1, 2, 3, 4, 5, 6]
1
two
3.0
4
three is not in list
[0, 1, 2, 3, 4]


## PROBLEM 1: Snap, Crackle, and Pop (15 pts)

Print numbers 0 ~ 15, but print "snap", "crackle", or "pop" after the number based on the following conditions:

1. Print "snap" after the number if it is divisible by 2.
2. Given the number is not divisible by 2, then print "crackle" if it is instead divisible by 3.
3. Regardless of 1 and 2, if the number is divisible by 5, then print "pop" that number of times.

For the sake of the problem, 0 is divisible by 2 and 3. You may need the modulus operator, `%`, which works the same way it does in Java. Yes, this is a modification of fizzbuzz, with more logic steps.

---

Example output:

```
0
snap
1
2
snap
3
crackle
4
snap
5
pop
pop
pop
pop
pop
6
snap
7
...
```





In [ ]:
# this is a function, by the way
def PROBLEM1():
    # Try to keep your code within 80 columns which is this line you see here  >
    # If you need more space, you can use backslash \ and get more space.
    # https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining

    # YOUR CODE GOES HERE
    i = 0
    while i <= 15:
      print(i)

      if i%2 == 0:
        print("snap")
      elif i%3 == 0:
        print("crackle")

      if i%5 == 0:
        for j in range(0,i):
          print("pop")

      i += 1;

    # no need to return anything
    return None

# DO NOT MODIFY
PROBLEM1()

0
snap
1
2
snap
3
crackle
4
snap
5
pop
pop
pop
pop
pop
6
snap
7
8
snap
9
crackle
10
snap
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
11
12
snap
13
14
snap
15
crackle
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop
pop


## PROBLEM 2: Fun with Lists (15 pts)

Given a list of strings, return the average length of strings whose lengths are greater than 5. Also, return a list containing the words with length less than or equal to 5.

You will need the `len()` function, which gives the length of a string.

---

For example, given:

`["hello", "this", "is", "example", "demonstrating", "problem", "statement"]`

The returned value is:

`9.0, ["hello", "this", "is"]`

In [ ]:
# input_list is an argument to the function, you can use it.
def PROBLEM2(input_list):
    # YOUR CODE GOES HERE
    count = 0
    total_length = 0
    shortlist = []

    for string in input_list:
      str_len = len(string)
      if str_len > 5:
        count += 1
        total_length += str_len
      else:
        shortlist.append(string)

    avg = total_length/count

    # you can return multiple values in python!
    return avg, shortlist

# DO NOT MODIFY
ex = ["hello", "this", "is", "example", "demonstrating", "problem", "statement"]
print(PROBLEM2(ex))

(9.0, ['hello', 'this', 'is'])



## Section 1 Appendix: More resources

Unfortunately we can't teach you the entire language here, so here are some more resources for learning Python:

COMS 1006

Boyd Python Language Companion:

https://ses.library.usyd.edu.au/handle/2123/21370

---

*The following resources are not supported by this class, but are included for your reference:*

Stanford CS231n Python/Numpy Tutorial

http://cs231n.github.io/python-numpy-tutorial/

Google's Python Class (taught in python2, just put parentheses after `print` for python3):

https://developers.google.com/edu/python

Codecademy's Python Tutorial (taught in python2, but python3 costs money):

https://www.codecademy.com/learn/learn-python

Dive Into Python 3:

https://diveintopython3.net/






# Section 2: Introduction to Numpy

Since this is a linear algebra course, we'll be dealing a lot with 1-dimensional vectors and 2-dimensional matrices. The obvious way to represent these in code are 1-dim and 2-dim arrays.

Let's look at representing the following vectors and matrices:

$\mathbf{u} = \begin{bmatrix} 1 & 0 & 4 & 6 \end{bmatrix}$

$\mathbf{v} = \mathbf{u}^T = \begin{bmatrix} 1 \\ 0 \\ 4 \\ 6 \end{bmatrix}$

$\mathbf{A} = \begin{bmatrix} 4 & 6 & 2 & 0 \\ 3 & 7 & 2 & 9 \\ 0 & 1 & 4 & 2 \\ 9 & 3 & 5 & 6 \end{bmatrix} $

In [ ]:
u = [[1, 0, 4, 6]]
v = [[1],
     [0],
     [4],
     [6]]
A = [[4, 6, 2, 0],
     [3, 7, 2, 9],
     [0, 1, 4, 2],
     [9, 3, 5, 6]]

Cool! Now, calculate $\mathbf{A^T A}$.

Just kidding, linear algebra is a major part of computer science, so there should be a package that can do this for us! Introducing... numpy.

Numpy turns lists into numpy arrays, on which we can do various linear algebra operations. Let's convert $\mathbf{u}$, $\mathbf{v}$, and $\mathbf{A}$ to numpy arrays first.


In [ ]:
# Example 6: numpy arrays
print(A)

u_arr = np.array(u)
v_arr = np.array(v)
A_arr = np.array(A)

print(A_arr)

[[4, 6, 2, 0], [3, 7, 2, 9], [0, 1, 4, 2], [9, 3, 5, 6]]
[[4 6 2 0]
 [3 7 2 9]
 [0 1 4 2]
 [9 3 5 6]]


Notice how numpy arrays print nicer! But that's not all of numpy's benefits:

In [ ]:
# Example 7: Accessing array entries

# Accessing a single element
print(A[1][3])          # for a 2D list, we access it normally
print(A_arr[1,3])       # for a 2D numpy array, we have this shortened form.

# Accessing a row
print(A[1])             # these are the same.
print(A_arr[1])

# Accessing a column
_col = []               # accessing a column is hard for a 2D list.
for arow in A:          # we have to iterate through each row and get each
    _col.append(arow[2])# value.
print(_col)

print(A_arr[:, 2])      # but this is very easy for a numpy array.
                        # ":" indicates we want values from all rows, while
                        # "2" specifies which column.
                        # This is familiar if you know MATLAB.


9
9
[3, 7, 2, 9]
[3 7 2 9]
[2, 2, 4, 5]
[2 2 4 5]


In [ ]:
# Advanced slicing
# The colon operator is actually very powerful. In general,
# A[begin:end:interval] where [begin, end)

# For 1D arrays:
ex = np.array([0,1,2,3,4,5,6,7,8,9])
print(ex[0:7])      # A slice from 0 (inclusive) to just before 7
print(ex[0:7:2])    # The same as above, but in intervals of 2

# This works for 2D arrays:
print(A_arr)
print(A_arr[0:2])       # Just the rows from 0 to just before 2
print(A_arr[0:2,0:2])   # Just the top left corner of matrix A_arr

[0 1 2 3 4 5 6]
[0 2 4 6]
[[4 6 2 0]
 [3 7 2 9]
 [0 1 4 2]
 [9 3 5 6]]
[[4 6 2 0]
 [3 7 2 9]]
[[4 6]
 [3 7]]


## PROBLEM 3: Slicing Practice (10 pts)

Given a matrix `input_matrix`, return a Numpy array that consists of every entry of A that has:

an even row index in the range [0, 7)

an odd column index in the range [3, 8)

This can be accomplished in a single line.



In [ ]:
def PROBLEM3(input_matrix):
    # YOUR CODE GOES HERE

    output_matrix = input_matrix[0:7:2, 3:8:2]

    return output_matrix

# DO NOT MODIFY
np.random.seed(3251)
example = np.random.randint(0, 10, (10,10))
print(example)
print(PROBLEM3(example))

[[5 3 0 3 6 9 3 2 0 6]
 [0 6 8 3 5 1 8 2 9 8]
 [5 3 3 9 0 4 8 6 3 9]
 [6 0 5 2 1 5 2 4 9 1]
 [6 7 3 6 1 0 1 4 4 9]
 [5 8 0 1 7 3 1 1 8 7]
 [0 8 7 2 5 3 8 9 6 5]
 [6 5 2 0 0 1 7 7 3 0]
 [8 0 0 3 6 5 3 8 0 8]
 [1 2 6 2 7 3 7 3 2 7]]
[[3 9 2]
 [9 4 6]
 [6 0 4]
 [2 3 9]]


## Numpy operations

Numpy has many functions useful for linear algebra, we'll cover them quickly here:

In [ ]:
# Matrix initializations:

# 5x5 array of...
# all zeros
np.zeros((5,5))
# all ones
np.ones((5,5))
# identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Matrix operations:

B = np.random.randint(0, 10, (4, 4))
print(B)
C = np.random.randint(0, 10, (4, 4))
print(C)

# matrix dimensions
print(B.shape)

# element-wise addition
print(B + C)
# element-wise subtraction
print(B - C)
# element-wise multiplication
print(B * C)
# element-wise division
print(B / C)
# scalar addition (subtraction, multiplication, etc.)
print(B + 2)

# matrix multiplication
print(np.dot(B, C))

# dot product of vectors
# dot product of horizontal vectors
D = np.array([[1,2,3,4]])
E = np.array([[5,6,7,8]])
print(np.dot(D, E.T))
# dot product of vertical vectors
D = np.array([[1],
              [2],
              [3],
              [4]])
E = np.array([[5],
              [6],
              [7],
              [8]])
print(np.dot(D.T, E))

# matrix transpose
print(B.T)

# Other operations can be found by Googling or referencing the Numpy
# documentation.

[[9 8 9 0]
 [5 8 7 2]
 [4 9 8 3]
 [2 3 1 5]]
[[0 2 0 7]
 [9 8 8 7]
 [3 8 9 2]
 [4 7 4 0]]
(4, 4)
[[ 9 10  9  7]
 [14 16 15  9]
 [ 7 17 17  5]
 [ 6 10  5  5]]
[[ 9  6  9 -7]
 [-4  0 -1 -5]
 [ 1  1 -1  1]
 [-2 -4 -3  5]]
[[ 0 16  0  0]
 [45 64 56 14]
 [12 72 72  6]
 [ 8 21  4  0]]
[[       inf 4.                inf 0.        ]
 [0.55555556 1.         0.875      0.28571429]
 [1.33333333 1.125      0.88888889 1.5       ]
 [0.5        0.42857143 0.25              inf]]
[[11 10 11  2]
 [ 7 10  9  4]
 [ 6 11 10  5]
 [ 4  5  3  7]]
[[ 99 154 145 137]
 [101 144 135 105]
 [117 165 156 107]
 [ 50  71  53  37]]
[[70]]
[[70]]
[[9 5 4 2]
 [8 8 9 3]
 [9 7 8 1]
 [0 2 3 5]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in true_divide


## Section 2 Appendix: More resources

**Numpy Resources:**

A useful Google search pattern is:

`Numpy (insert linear algebra function here)`

Complete Numpy documentation:

https://docs.scipy.org/doc/numpy/

Stanford CS231n Python/Numpy Tutorial:

http://cs231n.github.io/python-numpy-tutorial/

# Section 3: Implementing In-class Topics

This section mostly involves problems to implement topics learned in class. Any additional information required to complete each problem will be included in the instructions.

## PROBLEM 4: Simple Matrix Computation (20 pts)

Implement Problem 5, Subpart (a) as a function. For reference, the given expression was:

$\left( \begin{bmatrix} -1 & 0 & 2 \\ 0 & 1 & 4 \end{bmatrix}^T \begin{bmatrix} -2 \\ 1 \end{bmatrix} \right) \cdot \left( \begin{bmatrix} 3 & 1 \\ 0 & 0 \\ -2 & -1 \end{bmatrix} (\begin{bmatrix} 5 & -3 \end{bmatrix} + \begin{bmatrix} -4 & 2 \end{bmatrix})^T \right)$

For your convenience, variables have been provided for you, as the following:

$(A^T B) \cdot (C(D+E)^T)$

---

**IMPORTANT:** In numpy, `np.dot()` is matrix multiplication for 2D arrays, even if both elements are column vectors. Therefore, you must use the equivalent representation of $u \cdot v = u^T v$.

*ref*: BV Chapter 6.1 - 6.5, 10.1 - 10.2

In [ ]:
A = np.array([[-1, 0, 2],
             [0, 1, 4]])
B = np.array([[-2],
             [1]])
C = np.array([[3, 1],
              [0, 0],
              [-2, -1]])
D = np.array([[5, -3]])
E = np.array([[-4, 2]])

def PROBLEM4(A, B, C, D, E):
    # YOUR CODE GOES HERE

    #for my own internal reference:
    #matrix multiplication: A*B = C: A in R^(m*p), B in R^(p*n), C in R^(m*n)
    #A: 2x3 B: 2x1 C: 2x2 D: 1x2 E: 1x2
    #A.T: 3x2 B.T: 1x2 C.T: 2x2 D.T: 2x1 E.T: 2x1
    result = np.dot(A.T,B)
    temp = np.dot(C, (D+E).T)
    result = np.dot(result.T, temp)

    return result

# DO NOT MODIFY
print(PROBLEM4(A, B, C, D, E))

[[4]]


## PROBLEM 5: Matrix Computation Complexity (20pts)

As covered in Homework 1 Problem 4 and BV Chapters 6.5 & 10.1, an important consideration in linear algebra is computational complexity. In this problem, we demonstrate these issues.

**(a)** Implement the functions in HW1 Problem 4:

Let $A$, $B \in \mathbb R^{m \times n}$ and $x$, $y \in \mathbb R^n$.

ver 1: $z = (A+B)(x+y)$

ver 2: $z = Ax + Ay + Bx + By$

**(b)** Write a brief sentence comparing the two runtimes. Which version is faster, by how much?

In [ ]:

def P5VER1(A, B, x, y):
    # (a) Implement (A + B)(x + y) here.
    # YOUR CODE GOES HERE
    result = np.dot(A+B, (x+y).T)
    #result = (A+B)@(x+y).T
    return None

def P5VER2(A, B, x, y):
    # (a) Implement Ax + Ay + Bx + By here.
    # YOUR CODE GOES HERE=
    result = np.dot(A,x.T) + np.dot(A,y.T) + np.dot(B,x.T) + np.dot(B,y.T)
    #result = A@x.T + A@y.T + B@x.T + B@y.T
    return None

# DO NOT MODIFY
A = np.random.rand(1000, 2000)
B = np.random.rand(1000, 2000)
x = np.random.rand(1, 2000)
y = np.random.rand(1, 2000)

start = time.time()
P5VER1(A, B, x, y)
end = time.time()
print("Version 1 finished in:", end-start, "seconds.")

start = time.time()
P5VER2(A, B, x, y)
end = time.time()
print("Version 2 finished in:", end-start, "seconds.")

Version 1 finished in: 0.010020017623901367 seconds.
Version 2 finished in: 0.00690007209777832 seconds.


**(b)** Which version is faster, by how much?

Version 1 finished in: 0.006606340408325195 seconds.

Version 2 finished in: 0.0055882930755615234 seconds.

Version 2 is 16% faster than Version 1.

Version 1 took 3mn + n computations, so ~8000 computations.

Version 2 took 8mn + 3m computations, so ~16000 computations.

Version 2 should theoretically take twice as long as Version 1, but it was consistently faster than Version 1 computationally. This may be due to static costs of memory allocation and miscellaneous program runtime actions. But really, it's a mystery. I'd love some clarification on what's going on under the hood, but that's probably outside the scope of this class.




## PROBLEM 6: System of Linear Equations (20pts)

BV Chapter 8.3 discusses how to represent systems of linear equations in matrix form.

Consider the following chemical equation, where iron(II) sulfide combusts with oxygen to form iron(III) oxide and sulfur dioxide gas:

FeS + O$_2$ $\rightarrow$ Fe$_2$O$_3$ + SO$_2$

However, this equation needs to be balanced, as the number of each atom does not match between the left side and right side. For example, the left side has two oxygen atoms, while the right side has five.

If you are not familiar with chemical equation balancing, refer to Section 8.3.1 (p. 154) in the BV textbook. Additionally, refer to [this](https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_en.html) demo.

---

**(a)** Represent the above problem as a system of linear equations. Representing it as below should help:

$w$FeS + $x$O$_2$ $\rightarrow$ $y$Fe$_2$O$_3$ + $z$SO$_2$

You should get three equations, one for each element. Since you need four equations, also set $y = 1$.

**(b)** represent the system of linear equations as a matrix A and vector b. Define them as numpy variables.

**(c)** search Google or the numpy documentation for a numpy function that could solve the system of linear equations. It is in the `numpy.linalg` package. Use it to find the coefficients to balance the chemical equation.

**(d)** Use the coefficients above write the final, balanced equation. If the calculated coefficients are decimals, find a multiple where all coefficients are integers.

**(a):** edit this text cell and write out your system of equations below. $\LaTeX$ can be used by placing each equation between dollar signs.

(double-click and type in your answer here)


**Given:** y = 1

Fe: $w - 2y = 0$

O: $2x -3y - 2z = 0$

S: $w - z = 0$

In [ ]:
# (b)
# Define your matrix representation here as a numpy array:

A = np.array([[1, 0, -2, 0],
              [0, 2, -3, -2],
              [0, 0, 1, 0],
              [1, 0, 0, -1]])

b = np.array([0, 0, 1, 0])



In [ ]:
# (c)

def PROBLEM6(A, b):
    # Use the numpy function you found to solve the system of linear equations.
    # YOUR CODE GOES HERE

    coeffs = np.linalg.solve(A, b)

    return coeffs

# DO NOT MODIFY
print(PROBLEM6(A, b))

[2.  3.5 1.  2. ]


**(d)** write your final, balanced chemical equation (with integers) below.

4FeS + 7O$_2$ $\rightarrow$ 2Fe$_2$O$_3$ + 4SO$_2$

# Submission

Go to Runtime > Restart and run all... and confirm that all lab problem cells ran successfully.

Go to File > Print > Save as PDF. Submit the PDF as "Lab 1 Report" on Gradescope. Make sure to tag which page each question is in (code and results)! Otherwise, your answer will not be graded.

Go to File > Download .ipynb. Submit the file as "Lab 1 Code" on Gradescope.